[package]
name = "hyrule-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
botw-utils = "0.3.1"
colored = "2.0.0"
jstr = { git = "https://github.com/NiceneNerd/jstr" }
glob = "0.3.0"
lazy_static = "1.4.0"
msyt = { git = "https://github.com/NiceneNerd/msyt", rev = "f5d0c6e33cc8d12d66f1dd0d329ecf00bcbb9c51" }
path-slash = "0.1.4"
phf = { version = "0.10.0", features = ["macros"] }
rayon = "1.5.1"
roead = { git = "https://github.com/NiceneNerd/roead", rev = "d6e53848dfa69a188340576dda32bdd3f105bf7a" }
rstb = { version = "0.3.2", features = ["botw-data", "json"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
structopt = "0.3.23"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
