on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            name: linux
            ext: ~
          - os: windows-latest
            name: windows
            ext: .exe
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build
        run: cargo +nightly build --release
      - uses: Shopify/upload-to-release@v1.0.1
        name: Upload artifacts
        with:
          name: hyrule_builder_${{ matrix.platform.name }}${{ matrix.platform.ext }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          path: target/release/hyrule-builder${{ matrix.platform.ext }}
    env:
      CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1